W8D1/RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show] do 
    resources :subs, only: [:create]
  end 
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:create] do 
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :create] do 
    resources :comments, only:[:new, :index]
  end
  resources :comments, only:[:create]
end

W8D1/RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, presence:true 
    
    belongs_to :sub

    belongs_to :author,
        class_name: :User, 
        foreign_key: :user_id

    has_many :post_subs

    has_many :subs, 
        through: :post_subs, 
        source: :sub 
end

W8D1/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :require_logged_in, except: :show

    before_action :require_author, except: [:new, :create, :show]
    helper_method :is_author?
    def new
        @post = Post.new
        @post.sub_id = params[:sub_id]
        render :new
    end

    def create
        @post = Post.new(post_params)
        @post.sub_id = params[:sub_id]
        @post.user_id = current_user.id
        if @post.save
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def edit
        @post = Post.find_by(id: params[:id])
        render :edit
    end

    def update
        @post = Post.find_by(id: params[:id])
        if @post.update(post_params)
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :edit
        end
    end

    def show
        @post = Post.find_by(id: params[:id])
        render :show
    end

    def destroy
        @post = Post.find_by(id: params[:id])
        redirect_to sub_url(@post.sub_id)
        @post.destroy
    end

    private
    def post_params
        params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end

    def require_author
        redirect_to post_url(params[:id]) unless is_author?
    end

    def is_author?
        @post = Post.find_by(id: params[:id])
        if @post
            @post.user_id == current_user.id
        else  
            false
        end
    end

end

W8D1/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/RedditClone/app/views/posts/_form.html.erb
<% if type == 'new' %>
    <% action_url = sub_posts_url(@post.sub_id) %>
    <% button_text = 'New Post' %>
<% else %>
    <% action_url = post_url(@post) %>
    <% button_text = 'Edit Post' %>
<% end %>
<div>
    <form action="<%= action_url %>" method='post'>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <% if type == "edit" %>
            <input type="hidden" name="_method" value='patch'>
        <% end %>
        <label>Title: 
            <input type="text" name="post[title]" value="<%= @post.title %>">
        </label>
        <label>Url: 
            <input type="text" name="post[url]" value="<%= @post.url %>">
        </label>
        <label>Content: 
            <input type="textbox" name="post[content]" value="<%= @post.content %>">
        </label>
        <label >Subs: 
            <% Sub.all.each do |sub| %>
                <label><%= sub.title %>
                    <input 
                        type="checkbox" 
                        name="post[sub_ids][]" 
                        value="<%= sub.id %>"
                        <% if sub.id.to_s == params[:sub_id] %>
                            <%= 'checked' %>
                        <% end %>>
                </label>
            <% end %>
        </label>
        <button><%= button_text %></button>
    </form>
</div>

W8D1/RedditClone/app/views/posts/edit.html.erb
<%= render 'form', post: @post, type: 'edit' %>

W8D1/RedditClone/app/views/posts/new.html.erb
<%= render 'form', post: @post, type: 'new' %>

W8D1/RedditClone/app/views/posts/show.html.erb
<% if @post.url %>
  <h1><%= link_to(@post.title, @post.url) %></h1>
<% else %>
    <h1><%= @post.title %></h1>
<% end %>
<p><%= @post.content %></p>
<% if is_author? %>
    <a href="<%= edit_post_url(@post) %>"><button>Edit</button></a>
    <form action="<%= post_url(@post) %>" method="post">
      <input 
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <button>Delete</button>
    </form>
<% end %>