W6D5/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

W6D5/ninety_nine_cats/app/models/cat.rb
# require 'date'
class Cat < ApplicationRecord
    validates  :color, :name, :sex, presence: true

    # def age 
    #     date = Time.now.strftime("%d/%m/%Y %H:%M").split(' ').first 
    #     date = split('/').reverse
    #     b_day = self.birth_date.split('/') 
    #     date[1] - b_day[1]
    # end
end

W6D5/ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery unless: -> { request.format.json? }
end

W6D5/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index 
        @cats = Cat.all 
        render :index
    end

    def show 
        @cat = Cat.find_by(id: params[:id])
        render :show
    end

    def create 
        @cat = Cat.new(cats_params)
       
        if @cat.save 
            redirect_to cat_url(@cat.id)
        else 
            render :new
        end
    end

    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else  
        render :edit 
        end
    end

    def edit 
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end

    def new 
        @cat = Cat.new 
        render :new
    end

    private 

    def cats_params 
        params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
    end
end

W6D5/ninety_nine_cats/app/helpers/cats_helper.rb
module CatsHelper
end

W6D5/ninety_nine_cats/app/views/cats/edit.html.erb
<h1>Edit cat!</h1>

<form action="<%= cats_url %>" method="POST">
    <input type="hidden" name="_method" value = "PATCH">
      <label>Name:
             <input type="text" name="cat[name]" value="<%= @cat.name %>">
      </label>

      <input type="radio" name="cat[sex]" value="M" >
      <label>Male</label>
      <input type="radio" name="cat[sex]" value="F">
      <label>Female</label>

      <label for="cat_color">Color</label>
      <select name="cat[color]" id="cat_color">
              <option disabled selected>Select Color</option>
              <option value="red">red</option>
              <option value="gold">gold</option>
              <option value="black">black</option>
              <option value="mixed_color">mixed color</option>
      </select>

      <label for="birth_date">Birth Date</label>
      <input id="birth_date" type="date" name="cat[birth_date]">
      
      <label for="description">Description</label>
      <textarea name="cat[description]"></textarea>

      <input type="submit" value="add cat">
</form>

W6D5/ninety_nine_cats/app/views/cats/index.html.erb
<h1>All Of Our Cats</h1>

<ul>
    <% @cats.each do |cat| %>
        <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
        <br>
    <% end %>
</ul>

<a href="<%= new_cat_url %>">Add New Cat!</a>

W6D5/ninety_nine_cats/app/views/cats/new.html.erb
<h1>Add your cat!</h1>

<form action="<%= cats_url %>" method="POST">
      <label>Name:
             <input type="text" name="cat[name]" value="<%= @cat.name %>">
      </label>

      <input type="radio" name="cat[sex]" value="M" >
      <label>Male</label>
      <input type="radio" name="cat[sex]" value="F">
      <label>Female</label>

      <label for="cat_color">Color</label>
      <select name="cat[color]" id="cat_color">
              <option disabled selected>Select Color</option>
              <option value="red">red</option>
              <option value="gold">gold</option>
              <option value="black">black</option>
              <option value="mixed_color">mixed color</option>
      </select>

      <label for="birth_date">Birth Date</label>
      <input id="birth_date" type="date" name="cat[birth_date]">
      
      <label for="description">Description</label>
      <textarea name="cat[description]"></textarea>

      <input type="submit" value="add cat">
</form>

W6D5/ninety_nine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<table>
    
    <thead>
        <tr>
            <th colspan="3"><%= "#{@cat.name}'s Info" %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Attributes</th>
            <td>Birth Date</td>
            <td>Color</td>
            <td>Sex</td>
        </tr>
        <tr>
            <th scope="row">Value</th>
            <td><%= @cat.birth_date %></td>
            <td><%= @cat.color %></td>
            <td><%= @cat.sex %></td>
        </tr>
    </tbody>
</table>

<a href="<%= edit_cat_url(@cat) %>">Edit Cat Info!</a>
<a href="<%= cats_url %>">Back to All Cats!</a>